### ISSUE TITLE
3730 Cerrito deleted

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#18]
There were 4 planting records for Cerrito, but only one tree at that address.  I attempted to delete 3, but looks like all 4 records are now deleted.  Can you restore the record that includes tree care information from 11/15/15?  Thanks!

**Comment by lonsun** [comment]
Hi Liz,

I checked the existing system and found 1 planting in the system for 3730 Cerrito.  There were also 2 adoption requests for that same address, so I deleted the extra one.  I did not find any maintenance records at all.  

Further, the backups are done daily so if this all happened on the same day then your changes would not appear on any backups.  I did check the backup from 8am on 12/14 and 12/15 and found 3 plantings that belonged to 2 separate adoption requests.  This seems to confirm that you created a 4th planting, added maintenance records, then deleted it along with 2 others.

At this point the only way to resolve would be to manually add the maintenance records again to the remaining planting for that address.  

Let me know if there are any changes to the system that you would like to help make it clearer or to help avoid this type of thing in the future.  One thing I could see offhand is that there should be an easier way to see exactly which plantings belong to an adoption request and which adoption requests belong to a planting (like through links that connect them).  I'll add a ticket for this.

Please review and close this, unless you have any further questions.

**Comment by lizbittner** [comment]
Hi Lon,
Thanks for looking.  I thought I was being careful to only delete the 3
that did not have any maintenance records - but sounds like there were only
3 to begin with, not 4?  I didn't create a 4th planting.

I don't know, I'm a little confused.  I don't have the maintenance info for
that location any more - after they were entered, I tossed them.  Not a
major problem, I'll just add a November 15 maint record.

One thing that might help is to have the delete option available on the
report results page.  That way I could see all the records for that address
on one page, and then just delete duplicates without going back and forth -
since that page also shows info for the most recent maintenance record.

Or is there any way to have a "trash" so that the record is not really
totally deleted until we periodically empty the trash?  (Like with emails,
etc.)

Thanks!

**Comment by lonsun** [comment]
Liz, I created two more issues for the points you brought up.  I'll work on adding those.
