### ISSUE TITLE
Planting report by zone

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#20]
Is there a way to ask for a report for a few different zones, but not all zones?  (I tried listing with commas in between).  There is just one tree due for care in Zone 2.  It would be good if I could lump it with zone 3 for mapping purposes.

Thanks!

**Comment by lonsun** [comment]
Hi Liz,  I'm assuming this is for the maintenance this weekend so I'll get
it done by tomorrow morning.  Let me know if you need it sooner.

**Comment by lizbittner** [comment]
Hi Lon,
I've taken care of it for this week - I have all the groups mapped, so
there's no rush.  But it could be handy in the future (For now, I switched
the one zone 2 tree to zone 3 so that it would show up on the map.  Maybe
not the best solution, but it'll work for this week.)

Thanks!

**Comment by lonsun** [comment]
Okay, got it.  I'll knock some of the pending issues out in the next couple
of weeks.
