### ISSUE TITLE
Account not active

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#27]
When I tried signing in yesterday and today, says that my account is not active and I'm not able to access database.

**Comment by lonsun** [comment]
Sorry, try now.  I added the activation flow for new users and forgot to update something on the production app.  It should work now.

**Comment by lizbittner** [comment]
Okay, thanks.  This time I did not even have to log in.

**Comment by lonsun** [comment]
Ok. Thanks for the info.  I think I know why that happened and will fix it.

**Comment by lonsun** [comment]
The issue where a user is deactivated, then activated and able to log in is handled in #26.
