### ISSUE TITLE
missing data

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#33]
After our February 7 planting, I entered the trees that we planted into the database, but the data does not seem to be there.  Is it possible that the data is hidden somewhere, or did I make some other mistake?

**Comment by lonsun** [comment]
Hi Liz,

I found the following plantings that were added after feb 7th.  Are any still missing?

 house_number | street_name | planting_id |         created_at
--------------+-------------+-------------+----------------------------
         2836 | Esmond      |        2692 | 2016-02-08 02:36:38.130003
         2836 | Esmond      |        2691 | 2016-02-08 02:36:00.307024
         3108 | Lowell      |        2693 | 2016-02-08 02:38:09.03675
         3108 | Lowell      |        2695 | 2016-02-08 02:39:14.940712
         3108 | Lowell      |        2694 | 2016-02-08 02:38:43.590916
          720 | 38th        |        2696 | 2016-02-08 02:40:04.638531
         2849 | Gaynor      |        2684 | 2016-02-07 22:33:45.436111
         2849 | Gaynor      |        2683 | 2016-02-07 22:32:23.701847
         2729 | Clinton     |        2685 | 2016-02-07 22:34:23.83351
          919 | 33rd        |        2687 | 2016-02-07 22:37:36.660194
          919 | 33rd        |        2686 | 2016-02-07 22:36:22.441607
         2900 | McBryde     |        2689 | 2016-02-07 22:39:39.827209
         2900 | McBryde     |        2688 | 2016-02-07 22:38:35.601811
         2811 | Lincoln     |        2690 | 2016-02-08 02:34:32.946715
         3500 | Clinton     |        2697 | 2016-02-08 02:40:32.104726
         3510 | Cerrito     |        2700 | 2016-02-08 02:46:35.120284
          767 | 33rd        |        2699 | 2016-02-08 02:41:47.563137
          995 | Lassen      |        2703 | 2016-02-10 01:43:44.846391
          995 | Lassen      |        2702 | 2016-02-10 01:42:18.501433
          995 | Lassen      |        2701 | 2016-02-10 01:41:28.068874

**Comment by lizbittner** [comment]
Those are the ones I am talking about.  I wonder why I can't find them when
I do a search (report) by planting date, nor when I do a search by Adoption
Request?  Any thoughts?
