### ISSUE TITLE
4/16/11 planting date should be 10/22/11 (richmond Arbor day, not national arbor day).  I was changing them one by one, wondering if you're able to change all the dates at once?

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#4]

**Comment by lonsun** [comment]
You want me to update all plantings with event "Arbor Day 2011" to:

new event: Richmond Arbor Day 2011
planting date: 2011-10-22

Please confirm and I'll do the update at the database level.

**Comment by lizbittner** [comment]
Yes please.

**Comment by lonsun** [comment]
Done!
