### ISSUE TITLE
Add true/false option for (pre) assessed to adoption request

### ISSUE THREAD

**Issue by lizbittner** [lonsun/richmond_trees-admin#43]
It would make sorting easier when making a list of trees that still need to be assessed (by RT), to make a report that will exclude requests that have already been assessed (by RT).

**Comment by lonsun** [comment]
ok I'll add it

**Comment by lizbittner** [comment]
Thanks!  I hope this is not too laborious to do?

**Comment by lonsun** [comment]
@lizbittner this is done.  You can access that flag when creating or updating an adoption request.  Let me know any other changes you may want around this.

**Comment by lizbittner** [comment]
Hi Lon,
I'm not sure I described the issue clearly.  What you have done is not
functioning quite the way I was hoping.  Maybe we can go over it in person
some time.
